---
credentials:
  network-tacacs:
    backend: pass
    entry: network/credentials/network-tacacs
    username: operator

  terminal-tacacs:
    backend: pass
    entry: network/credentials/terminal-server
    username: operator
